FROM ubuntu:latest
WORKDIR /app
COPY ./ArqV1.txt ./
COPY ./ArqV1.txt ./ArqV1Container.txt
COPY ../Teste/ArqV2.txt ./
COPY ArqV3.* ./Wildcard/
COPY ./SrcDirectory ./SrcDirectory/
COPY ./SrcDirectory ./SrcDirectoryFile/File.txt
